resolver: lts-6.20
compiler: ghcjs-0.2.0.9006020_ghc-7.10.3
compiler-check: match-exact

packages:
  - '.'
  - location:
      git: https://github.com/fizruk/miso-aframe.git
      commit: 80564cb72991da47eb02f36870bf97ddbf180d89
    extra-dep: true
extra-deps:
  - miso-0.10.0.0

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006020_ghc-7.10.3:
        url: http://ghcjs.tolysz.org/lts-6.20-9006020.tar.gz
        sha1: a6cea90cd8121eee3afb201183c6e9bd6bacd94a
